import express from 'express';
import { signUp , signIn, getAllUsers, getFeedForUser , getAllPostFeedForUser, verifyToken, deleteUser} from '../../Controllers/userController.js';
import { isAuthenticated } from '../../Middlewares/authMiddleware.js';
const router = express.Router();
router.post('/signup', signUp);
router.post('/signin', signIn);
router.get('/all', isAuthenticated, getAllUsers);
router.get('/feed', isAuthenticated, getFeedForUser);
router.get('/feedall', isAuthenticated, getAllPostFeedForUser);
router.get('/verifytoken', verifyToken);
router.delete('/deleteUser', isAuthenticated, deleteUser);
export default router;